### ISSUE TITLE
Please document C side

### ISSUE THREAD

**Issue by SethDusek** [unbit/uwsgi-docs#301] opened 2016-03-31 21:33 UTC
It sucks that the C side of uwsgi isn't documented at all. I'm trying to modify a rust plugin but I can't find anything on the c api of uwsgi

**Comment by xrmx** [comment] 2016-04-01 07:24
This is a duplicate of #88. Feel free to read the discussion in the mailing list pointed in that bug. If you have any question again the mailing list is the right place to ask questions. Once you have sorted out things you are very welcome to contribute what you then know in the form of documentation. Also please use a different tone.

**Closed by xrmx** 2016-04-01 07:24 UTC

**Comment by SethDusek** [comment] 2016-04-02 00:42
Could you please atleast document wsgi_request? I've gone through some plugins yet I can't figure out what most of the stuff does. I don't know what app_id is, etc

**Comment by unbit** [comment] 2016-04-04 09:07
@SethDusek it is really a huge effort (now) to write developers documentation, i suggest you to start from the lua or the mono plugin to better understand the logic.

By the way app_id is a numeric identifier for hosting multiple applications in the same process. Something i do not think applies well to the rust environment.

Eventually, consider asking for specific fields of the structure in the mailing-list, there are lot of plugins developers that can help (and maybe at the end we will be able to have some useful material to writing dev-docs and extend this page: https://github.com/unbit/uwsgi-docs/blob/master/tutorials/WritingPlugins.rst)
